exp: TextClassification

mode: 
    - train

models:
    hf_text_classification_model:
      - distilgpt2

trainfpath: /home/ahatfield/finalproject/data/combined_train_randomized.tsv

validfpath: /home/ahatfield/finalproject/data/combined_validation_randomized.tsv

modelfpath: /home/ahatfield/finalproject/combined_distilgpt_model_randomized

numLabels: 2

device: cuda

id2label:
    1: 1
    0: 0