exp: TextClassification

mode: 
    - train

models:
    hf_text_classification_model:
      - distilbert-base-uncased

trainfpath: /home/ahatfield/finalproject/data/political_train_nonrandomized.tsv

validfpath: /home/ahatfield/finalproject/data/political_validation_nonrandomized.tsv

modelfpath: /home/ahatfield/finalproject/political_distilbert_model_nonrandomized

numLabels: 2

device: cuda